### ISSUE TITLE
The `locate_ieeg` is slow when using CT in original resolution

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-gui-addons#16]
When marking the position of micro-channels in original CT space the `locate_ieeg` gui can become really slow when refreshing the main four axes after a new position in CT space was clicked. The refresh can take 3 - 5 seconds, which effectively makes the whole channel-clicking process longer (it sometimes feels that more time is spent waiting for the refreshes than actual clicking).
Do you think this could be sped up?

**Comment by linnea-evanson** [comment]
Yes this is still the case for a CT which is not aligned to T1, which has size (512, 512, 640). It takes 3-5sec to update each time a new position is clicked.

**Comment by alexrockhill** [comment]
Thanks for reporting, this was on my to do list, I'll see if I can find some time to do that this week.

@larsoner would you happen to have 30 seconds to advise on PyQt time profiling approaches to try and make things run faster? If not, I'll figure it out but thought you might have some time saving advice

**Comment by larsoner** [comment]
I usually use [line_profiler](https://github.com/pyutils/line_profiler?tab=readme-ov-file#line_profiler) by decorating functions that might be problematic with `@profile` then `kernprof -lbv some_script.py`

**Comment by alexrockhill** [comment]
I haven't forgotten about this, I have some time to do this Thursday.
